In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv('loan_data.csv')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [ ]:
dataset.describe()

credit.policy      purpose     int.rate  installment  log.annual.inc  \
count    9578.000000  9578.000000  9578.000000  9578.000000     9578.000000   
mean        0.804970     1.944038     0.122640   319.089413       10.932117   
std         0.396245     1.686881     0.026847   207.071301        0.614813   
min         0.000000     0.000000     0.060000    15.670000        7.547502   
25%         1.000000     1.000000     0.103900   163.770000       10.558414   
50%         1.000000     2.000000     0.122100   268.950000       10.928884   
75%         1.000000     2.000000     0.140700   432.762500       11.291293   
max         1.000000     6.000000     0.216400   940.140000       14.528354   

               dti         fico  days.with.cr.line     revol.bal   revol.util  \
count  9578.000000  9578.000000        9578.000000  9.578000e+03  9578.000000   
mean     12.606679   710.846314        4560.767197  1.691396e+04    46.799236   
std       6.883970    37.970537        2496.930377  3.375619e+04    29.014417   
min       0.000000   612.000000         178.958333  0.000000e+00     0.000000   
25%       7.212500   682.000000        2820.000000  3.187000e+03    22.600000   
50%      12.665000   707.000000        4139.958333  8.596000e+03    46.300000   
75%      17.950000   737.000000        5730.000000  1.824950e+04    70.900000   
max      29.960000   827.000000       17639.958330  1.207359e+06   119.000000   

       inq.last.6mths  delinq.2yrs      pub.rec  not.fully.paid  
count     9578.000000  9578.000000  9578.000000     9578.000000  
mean         1.577469     0.163708     0.062122        0.160054  
std          2.200245     0.546215     0.262126        0.366676  
min          0.000000     0.000000     0.000000        0.000000  
25%          0.000000     0.000000     0.000000        0.000000  
50%          1.000000     0.000000     0.000000        0.000000  
75%          2.000000     0.000000     0.000000        0.000000  
max         33.000000    13.000000     5.000000        1.000000

In [ ]:
dataset.head(10)

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   
5              1         credit_card    0.0788       125.13       11.904968   
6              1  debt_consolidation    0.1496       194.02       10.714418   
7              1           all_other    0.1114       131.22       11.002100   
8              1    home_improvement    0.1134        87.19       11.407565   
9              1  debt_consolidation    0.1221        84.12       10.203592   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   
5  16.98   727        6120.041667      50807        51.0               0   
6   4.00   667        3180.041667       3839        76.8               0   
7  11.08   722        5116.000000      24220        68.6               0   
8  17.25   682        3989.000000      69909        51.1               1   
9  10.00   707        2730.041667       5630        23.0               1   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0  
5            0        0               0  
6            0        1               1  
7            0        0               1  
8            0        0               0  
9            0        0               0

In [ ]:
dataset[''].unique()

array([1, 0])

In [ ]:
dataset['purpose'].unique()

array(['debt_consolidation', 'credit_card', 'all_other',
       'home_improvement', 'small_business', 'major_purchase',
       'educational'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

lab = LabelEncoder()
dataset['purpose'] = lab.fit_transform(dataset['purpose'])

In [ ]:
dataset.head()

credit.policy  purpose  int.rate  installment  log.annual.inc    dti  fico  \
0              1        2    0.1189       829.10       11.350407  19.48   737   
1              1        1    0.1071       228.22       11.082143  14.29   707   
2              1        2    0.1357       366.86       10.373491  11.63   682   
3              1        2    0.1008       162.34       11.350407   8.10   712   
4              1        1    0.1426       102.92       11.299732  14.97   667   

   days.with.cr.line  revol.bal  revol.util  inq.last.6mths  delinq.2yrs  \
0        5639.958333      28854        52.1               0            0   
1        2760.000000      33623        76.7               0            0   
2        4710.000000       3511        25.6               1            0   
3        2699.958333      33667        73.2               1            0   
4        4066.000000       4740        39.5               0            1   

   pub.rec  not.fully.paid  
0        0               0  
1        0               0  
2        0               0  
3        0               0  
4        0               0

In [ ]:
dataset.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [ ]:
x = dataset.drop(columns = ['not.fully.paid'])
y = dataset['not.fully.paid']

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaling = StandardScaler()
x_train = scaling.fit_transform(x_train)
x_test = scaling.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,GradientBoostingClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

models = {
    'LogisticRegression': LogisticRegression(penalty='l2', C=1.0),
    'Naive Bayes' : GaussianNB(),
    'Support Vector Machine' : SVC(probability = True),
    'K-Nearest Neighbors' : KNeighborsClassifier(n_neighbors=5),
    'Decision Tree' : DecisionTreeClassifier(max_depth=10),
    'Random Forest' : RandomForestClassifier(max_depth=10, n_estimators=100, random_state=1),
    'Bagging' : BaggingClassifier(),
    'Gradient Boosting' : GradientBoostingClassifier()
}

trained_model_list = []
model_list = []
accuracy_list = []

y_train = y_train[:, 0] if len(y_train.shape) > 1 else y_train
y_test = y_test[:, 0] if len(y_test.shape) > 1 else y_test

def evaluate_model(y_test, y_pred):
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    return conf_matrix , class_report , accuracy*100

for model_name, model in models.items():
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    conf_matrix , class_report , accuracy = evaluate_model(y_test, y_pred)

    print(model_name)
    model_list.append(model_name)
    accuracy_list.append(accuracy)

    print('\nModel Training Performance')
    print("\nConfusion Matrix: \n", conf_matrix)
    print("\nClassification Report: \n", class_report)
    print("\nAccuracy Score: ", accuracy)

    print('=' * 35)
    print('\n')

greatest_acc = max(accuracy_list)
Index = accuracy_list.index(greatest_acc)

Best_model = model_list[Index]
print('Best Model for The Dataset is ',Best_model)

LogisticRegression

Model Training Performance

Confusion Matrix: 
 [[2393    4]
 [ 470    7]]

Classification Report: 
               precision    recall  f1-score   support

           0       0.84      1.00      0.91      2397
           1       0.64      0.01      0.03       477

    accuracy                           0.84      2874
   macro avg       0.74      0.51      0.47      2874
weighted avg       0.80      0.84      0.76      2874


Accuracy Score:  83.50730688935282


Naive Bayes

Model Training Performance

Confusion Matrix: 
 [[2178  219]
 [ 379   98]]

Classification Report: 
               precision    recall  f1-score   support

           0       0.85      0.91      0.88      2397
           1       0.31      0.21      0.25       477

    accuracy                           0.79      2874
   macro avg       0.58      0.56      0.56      2874
weighted avg       0.76      0.79      0.77      2874


Accuracy Score:  79.19276270006958


Support Vector Machine

Model Train

In [36]:
credit_policy = input('Credit Policy (Yes or No): ')
purpose = input('Purpose: ')
interest_rate = float(input('Interest Rate: '))
installment = float(input('Installment: '))
log_annual_income = float(input('Log of Annual Income: '))
dti = float(input('DTI Ratio: '))
fico = float(input('FICO score: '))
days_with_cr_line = float(input('Days with Credit Line: '))
revol_bal = float(input('Revolving Balance: '))
revol_util = float(input('Revolving Utilization Rate: '))
inq_last_6mths = float(input('Inquiries in last 6 months: '))
delinq_2yrs = float(input('Delinquencies in Past 2 years: '))
pub_rec = float(input('Public Records: '))

Credit Policy (Yes or No): 1
Purpose: 2
Interest Rate: 0.01
Installment: 800
Log of Annual Income: 11.69
DTI Ratio: 9.3
FICO score: 700
Days with Credit Line: 3000
Revolving Balance: 16000
Revolving Utilization Rate: 47.8
Inquiries in last 6 months: 0
Delinquencies in Past 2 years: 0
Public Records: 0


In [46]:
input_data = [credit_policy, purpose, interest_rate, installment, log_annual_income, dti, fico, days_with_cr_line, revol_bal, revol_util, inq_last_6mths, delinq_2yrs, pub_rec]
input_data = [float(value) for value in input_data]
y_pred = Logistic_Regression_model.predict([input_data])
print(y_pred)

if y_pred == 1:
  print("Loan Disapproved")
else:
  print("Loan approved")

[1]
Loan Disapproved
